url: http://qewdjs.com/ 
baseurl: http://qewdjs.com/    # /agency-jekyll-theme/

include: ["_pages"]

# Site settings
title: QEWD
company: M/Gateway Developments Ltd
title2: QEWD
email: your-email@domain.com
description: "#NodeJS based Integration Framework for the web: Quick Easy Web Development/ Quality Enterprise Web Development: #QEWD"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/robtweed/qewd
  - title: twitter
    url: https://twitter.com/qewdjs

# Postal address (add as many lines as necessary)
address:
  - line: # JS 
  - line: # World

# Build settings
markdown: kramdown
permalink: pretty
